Insert into Airplane(Airplane_id,Producer,Type)  Values(132,"Boeing",777);
Insert into Airplane(Airplane_id,Producer,Type)  Values(276,"Boeing",757);
Insert into Airplane(Airplane_id,Producer,Type)  Values(312,"Boeing",787);
Insert into Airplane(Airplane_id,Producer,Type)  Values(475,"Boeing",797);
Insert into Airplane(Airplane_id,Producer,Type)  Values(579,"Boeing",797);
Insert into Airplane(Airplane_id,Producer,Type)  Values(634,"Boeing",777);
Insert into Airplane(Airplane_id,Producer,Type)  Values(775,"Boeing",747);
Insert into Airplane(Airplane_id,Producer,Type)  Values(845,"Boeing",727);
Insert into Airplane(Airplane_id,Producer,Type)  Values(945,"Boeing",717);